<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Core_FileManagement</RootNamespace>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <Platforms>AnyCPU;x64</Platforms>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	  <PublishTrimmed>false</PublishTrimmed>
	  <PublishReadyToRun>false</PublishReadyToRun>

  </PropertyGroup>
  <ItemGroup>
    <None Remove="ViewModels\DriveViewModel.cs~RF1428454.TMP" />
  </ItemGroup>
	<ItemGroup>
		<TrimmableAssembly Include="System.Management" />
		<TrimmableAssembly Include="WinRT.Runtime" />
		<TrimmableAssembly Include="Microsoft.Windows.SDK.NET" />
	</ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fody" Version="6.9.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1721" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260317003" />
    <PackageReference Include="PropertyChanged.Fody" Version="4.1.0" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.5" />
    <PackageReference Include="System.Management" Version="10.0.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SettingManager\SettingsManager.csproj" />
  </ItemGroup>
  
</Project>